apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.votingapp.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.votingapp.serviceName }}
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.votingapp.type }}
  selector:
    name: {{ .Values.votingapp.podName }}
    app: {{ .Values.appName }}
  ports:
  - port: {{ .Values.votingapp.containerPort }}
    targetPort: {{ .Values.votingapp.containerPort }}
    nodePort: {{ .Values.votingapp.NodePort }}
